export type FoodCategory =
  | "meats"
  | "dairy"
  | "fruits"
  | "vegetables"
  | "nuts"
  | "grains"
  | "legumes"

export type Food = {
  name: string;
  protein: number;
  carbs: number;
  fats: number;
  calories: number;
  image: string;
  isVegan: boolean;
  category: FoodCategory;
};

export const foodElements: Food[] = [
  {
    name: "Eggs",
    protein: 6,
    carbs: 10,
    fats: 15,
    calories: 30,
    image: "https://www.tasteofhome.com/wp-content/uploads/2025/01/Pressure-Cooker-Hard-Boiled-Eggs_EXPS_TOHD24_258639_ChristineMa_3.jpg",
    isVegan: false,
    category: "dairy",
  },
  {
    name: "Orange",
    protein: 0,
    carbs: 40,
    fats: 5,
    calories: 30,
    image: "https://upload.wikimedia.org/wikipedia/commons/4/43/Ambersweet_oranges.jpg",
    isVegan: true,
    category: "fruits",
  },
  {
    name: "Chicken Breast",
    protein: 31,
    carbs: 0,
    fats: 3.6,
    calories: 165,
    image: "https://www.allrecipes.com/thmb/4xpAgIpdeRXHnn3CFwvLrZI10u0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/260445easy-mediterranean-baked-chicken-breastKimvideo4x3-6fc05b993afe4da5846bdc13a9861844.jpg",
    isVegan: false,
    category: "meats",
  },

  {
    name: "Beefsteak",
    protein: 27,
    carbs: 0,
    fats: 13,
    calories: 225,
    image: "https://www.allrecipes.com/thmb/OJ28fIFte6Pyg93ML8IM-APbu1Y=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/AR-14554-sirloin-steak-with-garlic-butter-hero-4x3-d12fa79836754fcf850388e4677bbf55.jpg",
    isVegan: false,
    category: "meats",
  },
  {
    name: "Broccoli",
    protein: 3,
    carbs: 7,
    fats: 0,
    calories: 35,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCF-tHnjvbNbE-4F74XT4JrRaxY6-C_SGPGg&s",
    isVegan: true,
    category: "vegetables",
  },
  {
    name: "Carrots",
    protein: 0.9,
    carbs: 9.6,
    fats: 0.1,
    calories: 41,
    image: "https://static01.nyt.com/images/2014/05/22/dining/Carrots-With-Orange-And-Cardamom/Carrots-With-Orange-And-Cardamom-jumbo.jpg",
    isVegan: true,
    category: "vegetables",
  },
  {
    name: "Almonds",
    protein: 21,
    carbs: 22,
    fats: 49,
    calories: 579,
    image: "https://images.immediate.co.uk/production/volatile/sites/30/2021/02/almonds-9e25ce7.jpg",
    isVegan: true,
    category: "nuts",
  },
  {
    name: "Cashews",
    protein: 18,
    carbs: 30,
    fats: 44,
    calories: 553,
    image: "https://cleanplatemama.com/wp-content/uploads/2023/05/roasted-cashews-thumbnail.jpg",
    isVegan: true,
    category: "nuts",
  },
  {
    name: "Baked Potatoes",
    protein: 1.9,
    carbs: 20.5,
    fats: 0.1,
    calories: 93,
    image: "https://www.spendwithpennies.com/wp-content/uploads/2025/05/1200-Oven-Roasted-Potatoes-SpendWithPennies.jpg",
    isVegan: true,
    category: "vegetables",
  },
  {
    name: "Hazelnuts",
    protein: 15,
    carbs : 17,
    fats: 61,
    calories: 630,
    image : "https://ohmyveggies.com/wp-content/uploads/2024/09/How-to-Roast-Hazelnuts-1200PX-SQUARE.jpg",
    isVegan: true,
    category: "nuts",
  },
  {
    name: "Milk (whole)",
    protein: 3.2,
    carbs: 4.8,
    fats: 3.3,
    calories: 61,
    image: "https://hips.hearstapps.com/hmg-prod/images/milk-6819e7e4c3689.jpg?crop=1.00xw:0.752xh;0,0.138xh&resize=1200:*",
    isVegan: false,
    category: "dairy",
  },
  {
    name: "Pistachio",
    protein: 20,
    carbs: 28,
    fats: 45,
    calories: 562,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Pistachio_vera.jpg/1200px-Pistachio_vera.jpg",
    isVegan: true,
    category: "nuts",
  },
  {
    name: "Rice",
    protein: 2.7,
    carbs: 28,
    fats: 0.3,
    calories: 130,
    image: "https://cdn.loveandlemons.com/wp-content/uploads/2020/03/how-to-cook-rice.jpg",
    isVegan: true,
    category: "grains",
  },
  {
    name: "Peas",
    protein: 5.4,
    carbs: 16,
    fats: 0.2,
    calories: 84,
    image: "https://www.onelovelylife.com/wp-content/uploads/2023/06/Frozen-Peas21-2.jpg",
    isVegan: true,
    category: "legumes",
  },
  {
    name: "Oats",
    protein: 17,
    carbs: 66,
    fats: 6.9,
    calories: 389,
    image: "https://images.contentstack.io/v3/assets/bltcedd8dbd5891265b/blt0cdb679f8a53702e/6665e9eeb8ee9e2ce92d7c82/4219130-Oatmeal-hero2.jpeg?q=70&width=3840&auto=webp",
    isVegan: true,
    category: "grains",
  },
  {
    name: "Lentils",
    protein: 9,
    carbs: 20,
    fats: 0.4,
    calories: 116,
    image: "https://www.themediterraneandish.com/wp-content/uploads/2024/10/TMD-How-To-Cook-Lentils-Leads-02.jpg",
    isVegan: true,
    category: "legumes",
  },
  {
    name: "Raspberry",
    protein: 1.2,
    carbs: 12,
    fats: 0.7,
    calories: 52,
    image: "https://aroma.bg/wp-content/uploads/2019/10/shutterstock_59196439.jpg",
    isVegan: true,
    category: "fruits", 

  },
  {
    name: "Blueberry",
    protein : 1,
    carbs : 14,
    fats : 0.3,
    calories : 57,
    image : "https://www.bbassets.com/media/uploads/p/l/30009286_13-fresho-blueberry.jpg",
    isVegan: true,
    category: "fruits",
  },
  {
    name: "Blackberry",
    protein : 1.4,
    carbs : 9.6,
    fats : 0.5,
    calories : 43,
    image : "https://i0.wp.com/post.healthline.com/wp-content/uploads/2020/03/black-raspberries-1296x728-header.jpg?w=1155&h=1528",
    isVegan: true,
    category: "fruits",
  },
  {
    name: "Banana",
    protein : 1.1,
    carbs : 23,
    fats : 0.3,
    calories : 89,
    image : "https://images.everydayhealth.com/images/diet-nutrition/bananas-nutrition-facts-1440x810.jpg?w=508",
    isVegan: true,
    category: "fruits",
  },
  {
    name: "White Cheese",
    protein : 20,
    carbs : 1.5,
    fats : 20,
    calories: 270,
    image : "https://www.arditairko.lt/uploads/images/catalog_src/white-cheese-types_src_1.jpg",
    isVegan: false,
    category: "dairy",
  },
];
